name: Londonproperty
favicon: null
layout_spectrum: 0.38809
typography_spectrum: 0.91637
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d1f67'
    - '#bdbdbf'
    - '#909092'
    - '#ca1a2f'
  brandStrength: 0.6930696573108435
  lightness: 0.14016554015688598
  saturation: 0.35388981690630317
  rhythmicContrast: 0.5747949772048742
purpose: []
